spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: yvycvydfgg@gmail.com
    password: jvrlucfxwbeevdnp
    properties:
      mail.smtp.starttls.enable: true
      mjaail.smtp.auth: true
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    url: jdbc:postgresql://${DB_HOST:localhost:${DB_PORT:5432}}/${DB_NAME:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
jwt:
  expiry: 30000000
  secret: asdfghjkl;'';lkjhgfdsaqwertyuiop[[poiuytrewqzxcvbnm,.,mnbvcxz



logging:
  level:
    org:
      hibernate:
        SQL=DEBUG:

